### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by albertsj1** [arjittw/vscode-musicplayer#1]
Hi.  I thought I'd give this a try, but I get a popup error message from vscode when trying to search and play music.

This is on osx 13.4.1 on a 2019 16" macbook pro.
I have mpv installed via homebrew.

vscode version 1.180.1

After I run music player: search music, select youtube and search for anything, I get an error that says:
```
"Command 'Music Player: Search Music' resulted in an error
Cannot find module '/Users/johnalb/.vscode/extensions/arjttw.musicplayer-1.0.0/package.json'
```

I can see mpv is launched and running in the background:
`mpv --idle --really-quiet --msg-level=ipc=v --no-video --no-audio-display --input-ipc-server=/tmp/node-mpv.sock`

Any thoughts?

**Comment by arjittw** [comment]
I think it's because of new vscode update, I'll try to fix it
ᐧ

**Comment by arjittw** [comment]
I just had to update npm packages, I have updated It will Work Now
Thanks

**Comment by albertsj1** [comment]
Thanks for taking the time to update it. Unfortunately, it's still not working for me.  I tried exactly what you show in the demo video, even searching for the same term 'fade', and I get the following error.

<img width="484" alt="Screenshot 2023-07-29 at 10 07 46 AM" src="https://github.com/arjittw/vscode-musicplayer/assets/141736/1c8f08b5-35aa-43a5-956d-44010bb40563">

**Comment by arjittw** [comment]
Fixed
