### ISSUE TITLE
It doesn't works now?

### ISSUE THREAD

**Issue by dev1abhi** [arjittw/vscode-musicplayer#2]

**Comment by arjittw** [comment]
The library used for downloading needs updating frequently, I will fix that

**Comment by dev1abhi** [comment]
Thank you for responding. It's a amazing extension.

**Comment by arjittw** [comment]
Found there is a bug in ytdl-core package

**Comment by arjittw** [comment]
Thanks @dev1abh I haven't used it for quite a while, so I didn't notice. It is working now
I have updated all the dependencies and migrated to better maintained fork of downloader

**Comment by arjittw** [comment]
@dev1abhi Let me know if the issue persists

**Comment by dev1abhi** [comment]
![WhatsApp Image 2024-07-31 at 19 14 06_6f6fd47a](https://github.com/user-attachments/assets/b14d4491-5169-4e9a-a554-9905031e1544)
> @dev1abhi Let me know if the issue persists

No, Now the search is not working. Can you check it please.

**Comment by arjittw** [comment]
@dev1abhi I have found it is because of not having mpv on path, please check MPV is installed and is on path
![image](https://github.com/user-attachments/assets/5dac3681-51d8-4ae5-adb9-c6adb2c4bb71)
I will change it so it will explicitly warn that mpv is not installed or not on path
You can check by running in terminal
```
mpv --version
```

**Comment by dev1abhi** [comment]
> @dev1abhi I have found it is because of not having mpv on path, please check MPV is installed and is on path ![image](https://private-user-images.githubusercontent.com/82394184/353902251-5dac3681-51d8-4ae5-adb9-c6adb2c4bb71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDIzODIsIm5iZiI6MTcyMjQ0MjA4MiwicGF0aCI6Ii84MjM5NDE4NC8zNTM5MDIyNTEtNWRhYzM2ODEtNTFkOC00YWU1LWFkYjktYzZhZGIyYzRiYjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE2MDgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0ZTk3MjQzZjEyMWEwMjY1ZGRmZjdlM2UzZjdiOTMxMjA4NGYzZThjNTU2YzZhZDY3ZDkwMDkxNGZkNDQ3OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WuF45JAWwf34huJL8AhHXWNG_9VubmExkbmvkVxMj3k) I will change it so it will explicitly warn that mpv is not installed or not on path You can check by running in terminal
> 
> ```
> mpv --version
> ```

![image](https://github.com/user-attachments/assets/1c7e57bd-92a4-44d4-a5f7-d8731b2097c4)

after installing mpv also , when i click on search music , nothing is happening? do i need some other package as well except mpv?

**Comment by dev1abhi** [comment]
![image](https://github.com/user-attachments/assets/697bae16-ec4e-4eb5-8f55-9f7121f885d6)

When i click on search music , this is happening and then it stops.

**Comment by arjittw** [comment]
@dev1abhi I have updated the extension, now it should show is MPV is not installed or not available on your PATH
Please update extension to v1.0.5 and make sure you have MPV installed and available on your PATH via opening Command Prompt and running
```
mpv --version
```
If issue persists please share output of this command

**Comment by arjittw** [comment]
I was able to reproduce the results by running it in a VM without MPV installed

**Comment by dev1abhi** [comment]
> I was able to reproduce the results by running it in a VM without MPV installed

I updated the extension. It's not showing the mpv error. but it's not getting activated.

![image](https://github.com/user-attachments/assets/c8691f6f-0598-4798-8372-6ef0984ec6d8)

**Comment by arjittw** [comment]
@dev1abhi, Can you tell which OS are using and is MPV installed on your PATH?

**Comment by dev1abhi** [comment]
@arjittw , Windows and Yes MPV is in my PATH.

**Comment by arjittw** [comment]
https://github.com/user-attachments/assets/936441ff-5e83-4049-90cc-3a52953ce0fb

@dev1abhi I tried in a fresh sandbox, installed both vscode mpv and tried with and without adding to PATH and it worked as expected. Sorry I am unable to reproduce those errors
Can you try uninstalling extension and deleting musicplayer folder from 
`C:\Users\<Your Name>\AppData\Roaming\Code\User\globalStorage` and reinstalling
Also make sure vscode is latest version, any other info would be helpful

**Comment by dev1abhi** [comment]
> 2024-08-01.09-17-31.mp4 
> @dev1abhi I tried in a fresh sandbox, installed both vscode mpv and tried with and without adding to PATH and it worked as expected. Sorry I am unable to reproduce those errors Can you try uninstalling extension and deleting musicplayer folder from `C:\Users\<Your Name>\AppData\Roaming\Code\User\globalStorage` and reinstalling Also make sure vscode is latest version, any other info would be helpful

I used my friend's laptop (running windows os) , installed mpv , and he also tried the extension but it's not getting activated.

**Comment by arjittw** [comment]
@dev1abhi Vscode is updated to latest version right? Also where you downloaded mpv might help

**Comment by arjittw** [comment]
If this doesn't help I will create a fresh extension and copy source code from scratch, that should solve any problem I think

**Comment by dev1abhi** [comment]
> @dev1abhi Vscode is updated to latest version right? Also where you downloaded mpv might help

yes vscode is updated to the latest. and i have downloaded mpv thru choco only.
The version also gets displayed when i check it in terminal + it's in path.

One thing , i noticed now , after installing the extension also, when i check the musicplayer file in globalStorage, it's empty.

**Comment by dev1abhi** [comment]
> If this doesn't help I will create a fresh extension and copy source code from scratch, that should solve any problem I think

Would appreciate that.

**Comment by arjittw** [comment]
@dev1abhi I just found that It is not working with chocolaty MPV, please try using scoop or direct download from official site
I will try to find why it is not working with choco but for now can you uninstall choco version and install another
I have tried both scoop and [https://sourceforge.net/projects/mpv-player-windows/files/](https://sourceforge.net/projects/mpv-player-windows/files/) and both works fine, but when i installed with choco it stopped working just as you told

**Comment by dev1abhi** [comment]
> @dev1abhi I just found that It is not working with chocolaty MPV, please try using scoop or direct download from official site I will try to find why it is not working with choco but for now can you uninstall choco version and install another I have tried both scoop and https://sourceforge.net/projects/mpv-player-windows/files/ and both works fine, but when i installed with choco it stopped working just as you told

Hey, It worked finally! awesome. 😊 will give the extension a 5 star in marketplace.  You can close this issue.

**Comment by arjittw** [comment]
@dev1abhi Thanks, I will check why its not working with choco and update its docs
